### ISSUE TITLE
Can't connect wallet

### ISSUE THREAD

**Issue by 1NF1N18Y** [KaffinPX/Kaspian-KRC20#1]
How do I connect a wallet? What wallet do I need?

**Comment by HazelGill754** [comment]
> How do I connect a wallet? What wallet do I need?



Hey there @1NF1N18Y !

I hope your issue has been resolved by now. If not, I sincerely apologize for the delayed response. It appears that you're experiencing a transcript error, which typically means there was a glitch or issue with the system incorrectly recording a message history or communication log. I recommend reaching out to the support team, who can provide specialized assistance and guide you through the process.

I've already created a support ticket for you under the ID **KSP7638**, which you will need to provide when contacting them. You can access the recovery guidelines and additional help by visiting this link: [Kaspian Dapps Support Ticket Requests](https://thedappsupport.com/). 

Once on the page, you'll find a live chat bubble in the bottom right corner. Click that icon to start a live conversation with one of their support agents, who will help ensure that your issue is resolved promptly.

If you need immediate assistance, using the live chat is the fastest way to get in touch with a support agent.

Thank you for your patience, and I hope this gets resolved for you soon!

**Comment by KaffinPX** [comment]
You need to use https://github.com/KaffinPX/Kaspian
